# Generated by Django 6.1 on 2026-08-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlog',
            name='ip_address',
        ),
    ]
