# Generated by Django 6.1 on 2026-08-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_remove_downloadlog_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlog',
            name='error_message',
        ),
    ]
