# Generated by Django 6.1 on 2026-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_remove_downloadlog_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmedia',
            name='resolution',
            field=models.IntegerField(blank=True, default=720, help_text='Video resolution in pixels', null=True),
        ),
        migrations.AddIndex(
            model_name='cachedmedia',
            index=models.Index(fields=['url_hash', 'resolution'], name='downloader__url_has_67463a_idx'),
        ),
    ]
